# Generated by Django 3.2.12 on 2022-02-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_move_data_to_new_master_distribution_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbookpackagecontent',
            name='dependencies',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='cookbookremote',
            name='cookbooks',
            field=models.JSONField(null=True),
        ),
    ]
